import = ["~/.config/alacritty/falcon.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[scrolling]
history = 10000
multiplier = 3

[window]
dynamic_padding = true
opacity = 0.99
startup_mode = "Windowed"

[window.padding]
x = 1
y = 0

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]

[cursor]
style = "Beam"
vi_mode_style = "Block"

[font.normal]
family = "BerkeleyMonoTrial Nerd Font Mono"

[font]
size = 12

[env]
TERM = "xterm-256color"
